API_KEY: yay
PUBLIC_KEY: ola
API_ENDPOINT: /api
DEBUG: true
COUCHDB_DOMAIN: "localhost:5984"

COUCHDB_LOGGER_USER:  "geoffreybot"
COUCHDB_LOGGER_PASSWORD: test


enabled_services: 
  - mailchimp_subscribe
  - post_form

apps:
  mailchimp: 
    API_KEY: 4f34ea944dd1e33a5452550789042f9c-us9
    DATA_CENTER: us9
    TEST_LIST_ID: f4b255a33a
  forms:
    API_KEY: eab9fd944139e3739e2c4e20f22b0c0fa80282ef5c601660063a7e3f497535e9
    USERNAME: eviltrout
    HOST: http://localhost:4000

CELERY:
  BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/1
  CELERY_TASK_SERIALIZER: json
  CELERY_ACCEPT_CONTENT:
    - json

  CELERY_RESULT_SERIALIZER: json
