API_KEY: "1234567890"
BROKER_URL: "sqla+sqlite:///celerydb.sqlite"

API_SERVER_HOST: "localhost"
API_SERVER_PORT: 8081

enabled_services: "mailchimp_subscribe"

apps:
  mailchimp:
    API_KEY: "4f34ea944dd1e33a5452550789042f9c-us9"
    DATA_CENTER: "us9"
    TEST_LIST_ID: "f4b255a33a"

